# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='super',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='thumb',
            field=models.ImageField(default='', upload_to='thumbs/'),
            preserve_default=False,
        ),
    ]
