# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160905_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='super',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category'),
        ),
    ]
