# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 22:01
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='richdesc',
            field=tinymce.models.HTMLField(default='init'),
            preserve_default=False,
        ),
    ]
