# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item_richdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='oldprice',
            field=models.DecimalField(decimal_places=2, default=99.8, max_digits=10),
        ),
    ]
